config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get 'home/index'
  root 'home#login'
  get '/about' => 'home#about'
  get '/policy' => 'home#policy'
  get '/contact' => 'home#contact'
  get '/search' => 'search#index'

  resources :users, only: [:show, :edit, :update] do
    member do
      get :home
      post :add_donation
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include PgSearch
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]
  enum favorite_cause: Organization.org_types
  multisearchable against: %i[first_name last_name nick_name location],
                  update_if: %i[
                    first_name_changed?
                    last_name_changed?
                    nick_name_changed?
                    location_changed?
                  ]

  has_many :user_favorite_organizations, dependent: :destroy
  has_many :favorite_organizations, through: :user_favorite_organizations, source: :organization
  has_many :donations, dependent: :destroy

  validates :email, uniqueness: true
  validates_presence_of :first_name, :last_name

  accepts_nested_attributes_for :user_favorite_organizations

  attr_accessor :organization_name
  attr_accessor :amount

  # rubocop:disable AbcSize
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.password = Devise.friendly_token[0, 20]
      user.nick_name = auth.extra.raw_info.short_name
      user.avatar_url = auth.info.image + "?type=large" # assuming the user model has a name
      user.uid = auth.uid
      user.provider = auth.provider
    end
  end
  # rubocop:enable AbcSize

  def badges
    donated_causes.uniq
  end

  def name
    "#{first_name} #{last_name}"
  end

  def donated_causes
    @donated_causes ||= Organization.joins(donations: :user).where("user_id = ?", id).pluck(:org_type)
  end

  ## NOTE: not yet stable. still experimenting. Need additional details. disable linting for this stand-in logic
  # rubocop:disable Metrics/AbcSize
  def donations_by_causes
    return @donations_by_causes if @donations_by_causes.present?

    @donations_by_causes = donated_causes.group_by(&:itself)
                                         .transform_values { |v| (v.size.to_f * 100 / donated_causes.size).round }
                                         .sort_by { |d_by_c| -d_by_c[1] }

    if @donations_by_causes.size > 4
      @donations_by_causes = @donations_by_causes[0..2] << ["others",
                                                            @donations_by_causes[3..-1].map(&:second).reduce(:+)]
    end
    @donations_by_causes
  end

  # @todo Move to a helper
  def profile_image
    avatar_url.present? ? avatar_url : "default_avatar"
  end

  # Donations made by friends/network
  # TODO: scope to network donations
  def network_donations
    Donation.all
  end

  # rubocop:enable Metrics/AbcSize
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
      @user = User.from_omniauth(request.env["omniauth.auth"])

      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication
        set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      else
        session["devise.facebook_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end

    def failure
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  helper_method :cause_logos # #will delete when we get real org logos.
  before_action :user, :donations_by_causes, only: %i[home show edit add_donation]
  before_action :ensure_current_user, :verify_access, only: %i[home edit]

  def show
    @badges = @user.badges
  end

  def edit
    @user_fav_orgs = @user.user_favorite_organizations[0..3]
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Successfully saved profile changes!"
      redirect_to @user
    else
      flash[:error] = @user.errors.full_messages.join(";  ")
      render "edit"
    end
  end

  def home
    redirect_to login_path unless user_signed_in?
    @network_donations = Donation.order(created_at: :desc).first(5)
  end

  # /users/:id/add_donation
  def add_donation
    organization = Organization.find_or_create_by(name: user_params[:organization_name])
    @donation = DonationService.create_donation(@user, organization, user_params[:amount])
    if @donation.save
      flash[:success] = "Successfully added donation!"
      # should redirect to user home page
    else
      flash[:error] = @donation.errors.full_messages.join(";  ")
      # should redirect to user home page with errors
    end
    redirect_to :home_user
  end

  private

  def user
    @user = User.includes(donations: :organization, user_favorite_organizations: :organization).find(params[:id])
  end

  def donations_by_causes
    @donations_by_causes = @user.donations_by_causes
  end

  def cause_logos
    {
      "animals" => "paw",
      "community" => "users",
      "education" => "graduation-cap",
      "environment" => "tree",
      "health" => "medkit",
      "human_rights" => "street-view",
      "human_services" => "child",
      "international" => "globe",
      "religion" => "chrome"
    }
  end

  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :location,
                                 :email,
                                 :philosophy,
                                 :favorite_cause_description,
                                 :organization_name,
                                 :amount,
                                 user_favorite_organizations_attributes: %i[id description])
  end

  def ensure_current_user
    redirect_to root_path unless user_signed_in?
  end

  def verify_access
    render_forbidden unless user_signed_in? && @user == current_user
  end

  def render_forbidden
    # TODO: Add 403 page and render it
    # render file: 'public/403.html', status: 403
    redirect_to root_path
  end
end

app/helpers/users/profile_edit_helper.rb
# frozen_string_literal: true

module Users
  module ProfileEditHelper
    def render_first_donation_bar(donations_by_causes:)
      cause, percent = donations_by_causes[0]
      render_donation_bar(cause: cause, percent: percent, highest: true)
    end

    def render_remaining_donation_bars(donations_by_causes:)
      donations_by_causes[1..-1].each do |cause, percent|
        concat(render_donation_bar(cause: cause, percent: percent))
      end
    end

    def render_donation_bar(cause:, percent:, highest: false)
      render "users/profile_edit/donation_bar", cause: cause, percent: percent, highest: highest
    end
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def show_location?
    if user_profile_page?
      "d-block"
    else
      "d-none"
    end
  end

  def user_profile_page?
    controller_name == "users" && action_name == "show"
  end

  def user_header_avatar_size
    user_profile_page? ? "user-header__image" : "user-header__image user-header__image--xs"
  end

  def user_header_info_alignment
    user_profile_page? ? "align-self-end" : "align-self-center"
  end
end

app/views/users/edit.html.erb
<%= javascript_include_tag "users/profile_edit" %>
<div class="user-profile-edit container-fluid">
<div class="profile-flash__container"></div>
<%= form_for(@user, remote: true, html: { class: "user-profile-edit__form" }) do |f| %>
  <%= render "users/profile_edit/profile_pic", form: f %>
  <div class="editable-content">
    <%= render "users/profile_edit/user_info", form: f %>
    <%= render "users/profile_edit/philosophy", form: f %>
    <%= render "users/profile_edit/donations_by_causes", form: f %>
    <%= render "users/profile_edit/favorite_organizations", form: f %>
  </div>
  <%= render "users/profile_edit/action_buttons", form: f %>
<% end %>
</div>

app/views/users/edit.js.erb
$('.profile-flash__container').html("<%= j render('shared/flash', type: 'error', content: flash[:error]) %>");

app/views/users/home.html.erb
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v5.0&appId=2244551272451887&autoLogAppEvents=1"></script>
<div class="user-home container-fluid">
  <% if flash[:success] %>
    <div class="profile-flash__container">
      <%= render("shared/flash", type: "success", content: flash[:success]) %>
    </div>
  <% end %>
  <%= render template: "layouts/user_header" %>
  <div class="user-home__sections">
    <div class="row user-home__section-titles">
      <div class="col-5 col-lg-3 user-home__section-title">
        MY NETWORK
      </div>
      <div class="col-6 offset-xl-1 user-home__section-title">
        MY FAVORITE ORGANIZATIONS
      </div>
    </div>

    <ul class="row nav user-home__section-titles user-home__section-titles--mobile" id="myTab" role="tablist">
      <li class="offset-2 col-4 nav-item user-home__section-title user-home__section-title--mobile">
        <a class="nav-link active" id="network-tab" data-toggle="tab" href="#network" role="tab" aria-controls="network" aria-selected="true">NETWORK</a>
      </li>
      <li class="col-4 nav-item user-home__section-title user-home__section-title--mobile row no-gutters">
        <a class="nav-link" id="favorite-tab" data-toggle="tab" href="#favorite" role="tab" aria-controls="favorite" aria-selected="false">FAVORITES</a>
      </li>
    </ul>

    <div class="row user-home__section-contents tab-content">
      <!-- network section -->
      <div class="col col-lg-3 tab-pane user-home__section-content active" id="network" role="tabpanel" aria-labelledby="network-tab">
        <div class="w-100 btn btn-primary new-donation-btn d-none d-lg-inline-block" data-target="#new-donation" data-toggle="modal">
          <%= fa_icon "plus", text: "Record my donation", class: "pr-4" %>
        </div>
        <div class="modal fade" id="new-donation" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <div class="modal-avatar">
                  <img class="rounded-circle user-header__image user-header__image--sm modal-avatar-img" src="<%= @user.profile_image %>" />
                </div>
                <h5 class="modal-title ml-2"><%= @user.name %></h5>
                <button type="button" class="close donation-modal-close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-container">
                <div class="modal-body">
                  <%= form_for @user, url: add_donation_user_path, method: :post  do |f| %>
                    <span>Amount</span>
                    <div class="field form-inline">
                      <span>$</span>
                      <div class="input-icon">
                        <%= f.text_field :amount, class: "form-control", placeholder: "0.00" %>
                      </div>
                  </div>
                  <div class="field form-inline">
                    <span>to</span>
                    <%= f.text_field :organization_name, class: "form-control", placeholder: "Organization name" %>
                  </div>
                    <div class="field p-visible mt-2 mb-2">Public - Visible to everyone
                      <span class="lock-icon">
                      <i class="fa fa-lock"></i>
                    </span>
                    </div>
                    <button type="submit" class="btn btn-primary">Record Donation</button>
                <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="btn btn-primary new-donation-btn--mobile fixed-bottom ml-auto d-lg-none" data-target="#new-donation" data-toggle="modal">
          <%= fa_icon "plus" %>
        </div>

        <% @network_donations.each do |donation| %>
          <div class="home-section-content">
            <div class="card user-home__card user-home__card--width-lg-300px">
              <div class="row">
                <%= link_to donation.user, class: "col-2 col-lg-3" do %>
                  <div class="mx-auto">
                    <%= image_tag(donation.user.avatar_url, alt: "rss feed", class: "rounded-circle avatar") %>
                  </div>
                <% end %>
                <div class="col-10 col-lg-9">
                  <div class="user-home__card__header">
                    <%= link_to donation.user.name, donation.user, class: "align-top user-home__card__donor-name heading" %>
                    <div class="donated-to-text"> Donated to</div>
<!--                    <a href="#" class="user-home__card__menu <%#= donation.user == current_user ? "" : "d-none" %>"><%#= fa_icon "ellipsis-v" %></a> -->
                  </div>
                  <div class="align-top user-home__card__organization body-medium"><%= donation.organization.name %></div>
                  <div class="user-home__card__time"><%= donation.created_at.strftime("%I:%M %p - %b %e, %Y") %></div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>

      <!-- favorite section -->
      <div class="col-12 col-lg-8 offset-xl-1 tab-pane user-home__section-content row no-gutters container" id="favorite" role="tabpanel" aria-labelledby="favorite-tab">
        <% Organization.first(6).each do |organization| %>
          <div class="card user-home__card user-home__card--width-lg-244px h-auto p-lg-0 mx-lg-1">
            <div class="fb-page" data-href="<%= organization.fb_url %>"
                 data-tabs="timeline"
                 data-width="450"
                 data-small-header="false"
                 data-adapt-container-width="true"
                 data-hide-cover="false"
                 data-show-facepile="true">
              <blockquote cite="https://www.facebook.com/GreatHeartsCommunity/" class="fb-xfbml-parse-ignore">
                <a href="<%= organization.fb_url %>">Loading - <%= organization.name %></a>
              </blockquote>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/users/show.html.erb
<%= javascript_include_tag "users/profile" %>
<div class="user-profile container-fluid">
  <% if flash[:success] %>
    <div class="profile-flash__container">
      <%= render("shared/flash", type: "success", content: flash[:success]) %>
    </div>
  <% end %>
  <%= render template: "layouts/user_header" %>
  <div class="profile-body profile-sections container-fluid">
    <%= render "users/profile_sections/badges" %>
    <%= render "users/profile_sections/donations_by_causes" %>
    <%= render "users/profile_sections/past_donations" %>
    <%= render "users/profile_sections/philosophy" %>
    <%= render "users/profile_sections/favorite_organizations" %>
  </div>
</div>