config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get 'home/index'
  root 'home#login'
  get '/about' => 'home#about'
  get '/policy' => 'home#policy'
  get '/contact' => 'home#contact'
  get '/search' => 'search#index'

  resources :users, only: [:show, :edit, :update] do
    member do
      get :home
      post :add_donation
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>GivingProfiles</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= stylesheet_link_tag "application", "http://fonts.googleapis.com/css?family=Roboto" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track': "reload" %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  </head>

  <body>
    <div>
      <%= render template: "layouts/header" %>
      <%= yield %>
      <%= render template: "layouts/footer" %>
    </div>

  </body>
</html>

app/views/layouts/footer.html.erb
<footer class="container-fluid footer <%= "footer--login" if login_page? %>">
  <div class="row d-flex align-items-end">
    <div class="footer__branding col-4 d-none d-md-block text-left footer__branding <%= "footer__branding__no-margin" if login_page? %>">
      GIVING
      PROFILES
    </div>
    <div class="footer__copyright text-md-center col col-md-4 col-lg-3">
      2017 - 2019 © Giving Profiles
    </div>
    <div class="footer__site_map col-8 col-md-4 col-lg-5 text-right">
      <a class="footer__site_map__link pr-3" href="/about">About</a>
      <a class="footer__site_map__link px-3 border-right border-left" href="/contact">Contact</a>
      <a class="footer__site_map__link pl-3" href="/policy">Policy</a>
    </div>
  </div>
</footer>

app/views/layouts/header.html.erb
<header class="page-header  <%= "page-header--no-margin" if login_page? %>">

  <div class='logo'>
    <a href="/">GIVING PROFILES</a>
  </div>

  <!-- This is just a place holder for now. -->
  <div class='header-search'>
    <%= form_tag(search_path, method: "get") do %>
      <%= fa_icon "search" %>

      <%= text_field_tag :query, nil, placeholder: "Search...", class: "border-0 header-search__input--no-background" %>
    <% end %>
  </div>

  <% if user_signed_in? %>
    <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "page-header__login-btn btn btn-secondary" %>
  <% elsif !login_page? %>
      <%= link_to "Log In", root_path, class: "page-header__login-btn btn btn-secondary" %>
  <% end %>
</header>

app/views/layouts/user_header.html.erb
<div class="user-header d-flex container-fluid">
  <div class="row w-100 no-gutters">
    <div class="col-12 row no-gutters">
      <%= image_tag(@user.profile_image, alt: "rss feed", class: "rounded-circle #{user_header_avatar_size}") %>
      <div class="user-header__info col <%= user_header_info_alignment %>">
        <h1 class="user-header__name d-none d-lg-block">
          <%= @user.name %>
        </h1>
        <p class="user-header__location #{show_location?} d-none d-lg-block">
          <%= @user.location %>
        </p>
        <% if user_profile_page? %>
          <div class="user-header__social-networks">
            <a href="#"><%= fa_icon "facebook-official", class: "fab" %></a>
            <a href="#"><%= fa_icon "envelope-square" %></a>
          </div>
        <% end %>
      </div>
      <div class="col ml-auto">
        <div class="user-header__nav-wrapper d-flex flex-column">
          <nav class="user-header__options justify-content-end d-flex">
            <a class="mx-2" href="#">
              <%= fa_icon "home" %>
              <span>Home</span>
            </a>
            <a href="#" class="mx-2 active">
              <%= fa_icon "user-circle" %>
              <span>Profile</span>
            </a>
            <a class="mx-2" href="#">
              <%= fa_icon "cog" %>
              <span>Settings</span>
            </a>
          </nav>
          <% if user_profile_page? %>
            <div class="edit-profile-button-container mx-2">
              <%= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-white align-self-end flex-row-reverse ml-auto" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <% if user_profile_page? %>
      <div class="col-6 user-header__info--margin-0 align-self-center d-lg-none">
        <h1 class="user-header__name">
          <%= @user.name %>
        </h1>
        <p class="user-header__location #{show_location?}">
          <%= @user.location %>
        </p>
      </div>
      <% if user_profile_page? %>
        <div class="col-6 user-header__nav-wrapper">
          <div class="edit-profile-button-container edit-profile-button-container--d-lg-none d-flex justify-content-end">
            <%= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-white align-self-end flex-row-reverse" %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>